Feature 10 - Sound
AihasasYadu/2D-Platformer-Game pull request #11
Opened 2020-07-21 22:45 UTC by AihasasYadu

Added Audio for:- 
>Menu Button Clicks
>Character's Landing
>BG Music for Lobby and Levels
>Game Over Overlay
>Level Complete Overlay
>Key Collection

2020-07-22 06:51 UTC, mayankgrover requested changes

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Audio/AudioManagerController.cs
> +    public void Play(string name)
enum

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Audio/AudioManagerController.cs
> +        foreach (Sound s in sounds)
few sounds sources - sources can be static (setup one time)

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Audio/AudioManagerController.cs
> +    }
void Stop(Sound sound) { 
.... 
}

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Audio/AudioManagerController.cs
> +    }
void StopAll* 
StopAllEffects()
StopTheme(){ ... }

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/GameOverController.cs
> +            Destroy(AudioManagerController.Instance);
get rid of this

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/HomeButtonController.cs
> +        Destroy(AudioManagerController.Instance);
remove

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Level_Over_Controller.cs
> +    public Image levelCompleteGIF;
fix

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Level_Over_Controller.cs
> +            AudioManagerController a = FindObjectOfType<AudioManagerController>();
fix

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Levels/LevelLoader.cs
> +        PlayerPrefs.SetInt(prefabHealth, 100);
hardcoding 
figure out better place for the health update logic

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/Levels/LevelLoader.cs
> +        FindObjectOfType<AudioManagerController>().sounds[0].source.volume = 0;
AudioManagerController.Instance.SetVolume(AudioType someref, float volume)

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/LobbyButtonsController.cs
> +        if(button.transform.position.x > 2000)
itween

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/LobbyButtonsController.cs
> +        GetComponent<Animator>().SetBool(mouseHoverAnimCondition, true);
cache

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/LobbyController.cs
> +        PlayerPrefs.SetInt(prefabHealth, 100);
dup

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/PlayerController.cs
> +        PlayerPrefs.SetInt(prefabLevel, SceneManager.GetActiveScene().buildIndex);
SaveController

2020-07-22 06:51 UTC, mayankgrover commented on Assets/Game Assets/AY_Scripts/RestartButtonController.cs
> +        if(AudioManagerController.Instance != null)
not needed

2020-07-23 23:30 UTC, AihasasYadu commented
replaced manual animation with iTween

2020-07-28 17:32 UTC, merged